### ISSUE TITLE
Use the commit sha1 for view in context

### ISSUE THREAD

**Issue by SebastienElet** [nfroidure/jsarch#3]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior

When i use the view in context, for example https://github.com/nfroidure/siso/blob/master/src/index.js#L81-L86, it use master branch.

In the futur, if i browse the version 1.2, all links may be wrong in `ARCHITECTURE.md`, here it should be https://github.com/nfroidure/siso/blob/c4ab54ef246d92ab48df9ac8c6826d03ca6d594e/src/index.js#L81-L86

💡 You can use `y` key on github to do the switch

### Steps to reproduce the behavior

Open any link `view in context`, they point on master.

### Use cases

- [ ] I will do it

**Comment by nfroidure** [comment]
I kept it simple by just making the links relative.

It has the nice side effect to change the ARCHITECTURE file only when the lines of the architecture notes change.

Also, it is not possible to know the commit sha1 before committing so how could i add it to links?

Finally, due to relative nature of the view in context links, if you link to the ARCHITECTURE.md file with the commit sha1 in the URL, your "view in context" links are then having the sha1 in their path. For example https://github.com/nfroidure/siso/blob/f5cfcdde15bad61cb1cf1c3ae7b42e32b07b7842/ARCHITECTURE.md

So i think i won't add this feature since i'm not sure it is even feasible and it fits my use cases as is.
